name: home_finder
description: "A real estate app for finding your ideal home"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0




flutter:


  uses-material-design: true

  assets:
    - assets/images/welcome_screen.jpg
    - assets/images/user.jpg
    - assets/images/house1.jpg
    - assets/images/house2.jpg
    - assets/images/house3.jpg
    - assets/images/details.png
    - assets/images/maison.jpeg
    - assets/images/maison2.jpeg
    - assets/images/maison3.jpeg
    - assets/images/maison4.jpeg
    - assets/images/maison5.jpeg
    - assets/images/profile.jpeg











